### ISSUE TITLE
Improve JS module load

### ISSUE THREAD

**Issue by impulse** [ameistad/tailwind-colors#1]
Loading in a config with require would result in following error:
> ReferenceError: require is not defined

I am not sure [resolveConfig](https://github.com/tailwindcss/tailwindcss/pull/877) would help in this situation, so I'd suggest to match something like

`/require\(.+?\)/g`

to remove any require from the loaded string.

**Comment by ameistad** [comment]
I agree, just removing every line with require will work. Let me know if you want to provide a pull request for this. Thanks for reporting the issue regardless.
