### ISSUE TITLE
Support stateful URL to enable sharing via a link

### ISSUE THREAD

**Issue by james2doyle** [ameistad/tailwind-colors#11]
Basically, if you can encode the current config into the URL, you can enable a cheap but useful "share" feature. I've used [masotime/json-url](https://github.com/masotime/json-url#readme) in the past to enable this for a [Vuex State](https://gist.github.com/james2doyle/67cddc077f67227981c2710abab66609#file-vuex-statefulurl-js-L43-L55).

I think if you just added an "updateURL" function/method call after [all your handlers](https://github.com/ameistad/tailwind-colors/blob/master/src/App.vue#L84-L98) you can enable this quite quickly.

If you want, I can take a crack at this. Interested to hear what you think

**Comment by ameistad** [comment]
Yes, that sounds useful. I would love a PR on that feature if you have time.
