### ISSUE TITLE
Add quotes to property name

### ISSUE THREAD

**Issue by gilesbutler** [ameistad/tailwind-colors#4]
Hey @ameistad,

Thanks for the awesome tool.

Would it be possible to add quotes to the property names so the resulting JS is valid?

I added some props with dashes and I get a syntax error when I try to use the compiled JS file...

<img width="1856" alt="Tailwind_Colors" src="https://user-images.githubusercontent.com/790734/65528190-d4c6f400-deeb-11e9-8e84-792c3654a11c.png">

**Comment by ameistad** [comment]
Hi @gilesbutler! You are very welcome, and thanks for your interest. 

I think that it's best that the default option is still without quotes. But it might be a good idea to check if its valid identifier name and wrap it in quotes if it's not. I'll be happy to accept a pull request if you want to look into it :) Maybe something like https://www.npmjs.com/package/is-var-name could be used. 

Let me know what you think.

**Comment by gilesbutler** [comment]
Hey @ameistad,

No worries, thanks for the response. Yep makes sense. I'll let you know if I get round to a PR. I don't think I'd use the tool enough tbh but just thought I'd point it out encase it helped :)
